name: Commit checks and deploy runner  # название workflow
on: # запуск workflow при push и pull-request в ветку master.
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-and-test: # описываем процесс сборки и тестирования проекта
    name: Building and Testing the app
    runs-on: ubuntu-22.04 # определяем runner процесса - виртуальную машину ubuntu-22.04
    steps: #определяем шаги, которые необходимо выполнить в этой job
      - name: Checkout # для начала копируем репозиторий на виртуальную машину с помощью
        # доступного на Github Marketplace action https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4
      - name: Setup JDK # устанавливаем рабочее окружение - JVM temurin с Java 17 и Gradle
        # Для этого также используем action с Github Marketplace https://github.com/marketplace/actions/setup-java-jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: build, tests # Шаг, на котором будет выполняться сборка и тестирование проекта.
        # Описываем его с помощью команд, которые выполнятся на виртуальной машине ubuntu-22.04
        run: |
          chmod +x gradlew
          ./gradlew build

  prepare-environment:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      # Клонируем репозиторий на self-hosted раннер
      - name: Checkout code
        uses: actions/checkout@v4

      # Проверяем наличие docker-compose.yml в папке docker/
      - name: Validate docker-compose file
        run: ls -la docker/docker-compose.yml

      # Останавливаем контейнеры, указывая путь к файлу
      - name: Stop and remove containers
        run: docker-compose -f docker/docker-compose.yml down

      # Очищаем Docker
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and start containers
        run: |
          docker-compose -f docker/docker-compose.yml build 
          docker-compose -f docker/docker-compose.yml up -d
          
